# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FHExpandTableViewDemo' do
    pod 'Masonry'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FHExpandTableViewDemo

  target 'FHExpandTableViewDemoTests' do
    # Pods for testing
  end

  target 'FHExpandTableViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
